# Generated by Django 5.2.12 on 2026-03-08 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrecord',
            name='support_person',
            field=models.ForeignKey(limit_choices_to={'role': 'SUPPORT'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
