# Generated by Django 5.2.12 on 2026-03-10 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='coordinator',
            field=models.ForeignKey(limit_choices_to={'role': 'COORDINATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='instructors',
            field=models.ManyToManyField(limit_choices_to={'role': 'INSTRUCTOR'}, related_name='instructor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='pseudopilots',
            field=models.ManyToManyField(limit_choices_to={'role': 'PSEUDOPILOT'}, related_name='pseudopilot_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='student_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='main_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_sessions', to='courses.room'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='pseudopilot_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pseudopilot_sessions', to='courses.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='simulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='courses.simulator'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('simulator', 'room_type')},
        ),
    ]
