# Generated by Django 5.2.12 on 2026-03-10 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='coordinator',
            field=models.ForeignKey(limit_choices_to={'role': 'ACADEMIC_COORDINATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
